# n 대입시 n2 디멘션 만들기  

In [1]:
import numpy as np


def n_size_ndarray_creation(n, dtype=np.int):
    x = [[0]*n for _ in range(n)]
    return x
print(n_size_ndarray_creation(5))

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [3]:
import numpy as np


def n_size_ndarray_creation(n, dtype=np.int):
    return np.arange(n**2).reshape(n,n)
    
print(n_size_ndarray_creation(5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 0만 이루어진, 1로만 이루어진 비어진 np생성

In [12]:
import numpy as np

import random
def zero_or_one_or_empty_ndarray(shape, type =0,dtype=np.int):
    x,y = shape
    if type == 0 :
        temp = np.array([[0]*x for _ in range(y)] )

    elif type == 1:
        temp = np.array([[1]*x for _ in range(y)])
    else :
        temp = np.array([[random.random()]*x for _ in range(y)])
    return temp

print(zero_or_one_or_empty_ndarray((2,2),))


[[0 0]
 [0 0]]


In [ ]:
import numpy as np

import random
def zero_or_one_or_empty_ndarray(shape, type =0):
    x,y = shape
    if type == 0 :
        return np.zeros(shape = shape, dtype = dtype)
    elif type == 1:
        return np.ones(shape = shape, dtype = dtype)
    else :
        return np.empty(shape = shape, dtype = dtype)
    return temp

print(zero_or_one_or_empty_ndarray((2,2),))

# n_row에 맞춰서 행의 수를 조정해서 출력 

In [ ]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten if n_row==1 else X.shape(n_row, -1)
# 1일때는 그냥 압축 1줄 출력
# shape (줄수, -1 == 자동으로 배열해주라)
    

    


# 배열을 세로1줄 or 가로 1줄로 하나로 합쳐라 

In [8]:
import numpy as np

def concat_ndarray(a1, b1, t):
    if t == 0 :
        return np.concatenate((a1,b1), axis = 0)
    else :
        return np.concatenate((a1,b1), axis = None)
    

a = np.array([1, 2])
b = np.array([5, 6, 7])
print(concat_ndarray(a, b, 1))


AxisError: axis 3 is out of bounds for array of dimension 1

# 정규화시켜라 

In [ ]:
# x 데이터 생성

x = np.arange(12, dtype = np.float32).reshape(4,3)

def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row, n_column =X.shape
    # shape : row column 즉시 뽑아주는 함수임을 기억 
    if axis == 99 :
        x_mean = np.mean(X)
        # 평균 즉시 계산
        x_std = np.std(X)
        # 표편 즉시 계싼
        Z = (X-x_mean) / x_std
    if axis == 0:
        x_mean = np.mean(X,9)
    X = 


# 

In [ ]:
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename, "wb")
    np.save("npy_test", file_test)




# 

In [ ]:
def boolean_index(X, condition):
    
    condition = eval(str("X")+condition)
    return np.where(condition)

X = np.random.uniform(0,1,5)

In [ ]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

# 가장 큰값을 출력하시오

In [22]:
import numpy as np
X = np.array(range(100)
X =  np.argsort()[::-1]

SyntaxError: invalid syntax (<ipython-input-22-3bebea081d67>, line 3)

In [19]:
import numpy as np
X = np.array(range(100))

def get_n_largest_values(X, n):
    x = np.argsort()[::-1]
    return x
print(get_n_largest_values(X, 3))

TypeError: _argsort_dispatcher() missing 1 required positional argument: 'a'