In [5]:
import numpy as np

#### all & any

In [ ]:
- 마찬가지 6챕터에서 배운 np 값의 전체 비교도 가능

In [6]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [ ]:
- 하나라도 조건 만족 값 any

In [8]:
np.any(a>5), np.any(a<0)

(True, False)

In [ ]:
- 전부다 조건 만족 값 all

In [9]:
np.all(a>5) , np.all(a < 10)

(False, True)

#### comparision operation

In [10]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b 

array([False,  True, False], dtype=bool)

In [11]:
test_a == test_b 

array([False, False, False], dtype=bool)

In [10]:
(test_a > test_b).any()

True

# np.where

In [ ]:
a>0 조건이 맞다면 b를 출력 , 아니면 2를 출력


In [15]:
a

array([ 1.,  3.,  0.])

In [16]:
np.where(a > 0, 3, 2) 

array([3, 3, 2])

In [ ]:
이 밑의 기법 때문에 공부하는거 조건에 맞는 모든 index 값을 출력 가능

In [18]:
np.where(a>0)

(array([0, 1]),)

In [22]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.where(a>10)

(array([6, 7, 8, 9]),)

In [44]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False], dtype=bool)

In [46]:
np.isfinite(a)

array([ True, False, False], dtype=bool)

#### argmax & argmin

In [ ]:
- 최대값 최소값 찾는데 index로 반환해준다.

In [19]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

(5, 0)

In [ ]:
밑으것은 축 기준 탐색인데 axis =1은 세로 탐색

-> 7 88 76

밑의 것은 열 기준 탐색 

->  0 0 2 2

In [26]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))